# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Arizul-Islam/PingKmon/releases/download/v2.0.0/PingKmon_2.0.0_x64-setup.exe
    InstallerSha256: 99A7E3A26EBB553BF6F3722E57B275C9ED87992448D38F628001742405751C52
ManifestType: installer
ManifestVersion: 1.6.0
