# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Arizul-Islam/PingKmon/releases/download/v2.0.1/PingKmon_2.0.1_x64-setup.exe
    InstallerSha256: BF3F4FCB1103A9BE118211EA0BF087C6DA1AEE20DDBF526BECDA7B0A0C64A4BB
ManifestType: installer
ManifestVersion: 1.6.0
