# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.4
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
