# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.3
PackageLocale: en-US
Publisher: ARIZUL
PublisherUrl: https://github.com/Arizul-Islam
PublisherSupportUrl: https://github.com/Arizul-Islam/PingKmon/issues
Author: ARIZUL
PackageName: PingKmon
PackageUrl: https://github.com/Arizul-Islam/PingKmon
License: Freeware
Copyright: All Rights Reserved (c) 2026 ARIZUL
ShortDescription: Native Windows Network Latency & Multi-Host Diagnostic Software
Description: PingKmon is a modern, high-performance network diagnostic and latency monitoring tool built specifically for Windows with Tauri 2.0 and Rust.
Moniker: pingkmon
Tags:
  - ping
  - network
  - latency
  - diagnostics
  - traceroute
  - speedtest
  - monitor
  - packet-loss
  - freeware
ReleaseNotesUrl: https://github.com/Arizul-Islam/PingKmon/releases/tag/v2.0.3
ManifestType: defaultLocale
ManifestVersion: 1.6.0
