# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Arizul-Islam/PingKmon/releases/download/v2.0.3/PingKmon_2.0.3_x64-setup.exe
    InstallerSha256: 57BA09AB1B8C7D2605FB8DDFB7F19975F27197938EB07242A0CF096F428962A6
ManifestType: installer
ManifestVersion: 1.6.0
