# Created with WinGet Manifest Creator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Arizul.PingKmon
PackageVersion: 2.0.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Arizul-Islam/PingKmon/releases/download/v2.0.2/PingKmon_2.0.2_x64-setup.exe
    InstallerSha256: 0AF78674C09D5F428FAC67C265EFAE7937F2C527EF0224526CC562076435ED9F
ManifestType: installer
ManifestVersion: 1.6.0
